format_version: v1.0
type: UniqueComponent
attributes: {id: FreeRTOS}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: FREERTOS_MEMORY_MANAGEMENT_CHOICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysNetPic32mzw1, value: Heap_3}
  - type: Integer
    attributes: {id: FREERTOS_PERIPHERAL_CLOCK_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '100000000'}
  - type: Integer
    attributes: {id: FREERTOS_TICK_RATE_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sysWifiPic32mzw1, value: '250'}
- type: ElementPosition
  attributes: {x: '30', y: '360', id: FreeRTOS}
